export const data = [
  {
    id: 1,
    name: "Item 1",
    description: "This is item 1",
    active: true,
  },
  {
    id: 2,
    name: "Item 2",
    description: "This is item 2",
    active: false,
  },
  {
    id: 3,
    name: "Item 3",
    description: "This is item 3",
    active: true,
  },
  {
    id: 4,
    name: "Item 4",
    description: "This is item 4",
    active: true,
  },
  {
    id: 5,
    name: "Item 5",
    description: "This is item 5",
    active: false,
  },
  {
    id: 6,
    name: "Item 6",
    description: "This is item 6",
    active: true,
  },
  {
    id: 7,
    name: "Item 7",
    description: "This is item 7",
    active: false,
  },
  {
    id: 8,
    name: "Item 8",
    description: "This is item 8",
    active: true,
  },
  {
    id: 9,
    name: "Item 9",
    description: "This is item 9",
    active: false,
  },
  {
    id: 10,
    name: "Item 10",
    description: "This is item 10",
    active: true,
  },
  {
    id: 11,
    name: "Item 11",
    description: "This is item 11",
    active: true,
  },
  {
    id: 12,
    name: "Item 12",
    description: "This is item 12",
    active: false,
  },
  {
    id: 13,
    name: "Item 13",
    description: "This is item 13",
    active: true,
  },
  {
    id: 14,
    name: "Item 14",
    description: "This is item 14",
    active: true,
  },
  {
    id: 15,
    name: "Item 15",
    description: "This is item 15",
    active: false,
  },
  {
    id: 16,
    name: "Item 16",
    description: "This is item 16",
    active: true,
  },
  {
    id: 17,
    name: "Item 17",
    description: "This is item 17",
    active: false,
  },
  {
    id: 18,
    name: "Item 18",
    description: "This is item 18",
    active: true,
  },
  {
    id: 19,
    name: "Item 19",
    description: "This is item 19",
    active: false,
  },
  {
    id: 20,
    name: "Item 20",
    description: "This is item 20",
    active: true,
  },
];
